---
title: "Client Report - Environment on Growth"
subtitle: "Course DS 250"
author: "Trot Markle"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---
```{python}
import pandas as pd
from palmerpenguins import load_penguins
from lets_plot import *

LetsPlot.setup_html()
```


## Elevator pitch
The antartic environment of the Biscoe island has caused the penguins from Biscoe to be materially larger than the penguins from Torgensen and Dream.

```{python}
#| label: project-data
#| code-summary: Read and format project data

# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

df = pd.read_csv("https://raw.githubusercontent.com/byuidatascience/data4python4ds/master/data-raw/mpg/mpg.csv")

```

__Highlight the Questions and Tasks__
The penguins on Biscoe were signifigantly larger than the penguins from Tergensen and Dream.

## Question|Task 1
Recreate the example chart from PY4DS: CH2 Data Visualization of the textbook.

The freezing temperatures of the artic environment on Briscoe island has forced the Penguins to grow larger to produce enough heat and hunt enough to survive their harsh environment. Briscoe island enabled and forced the penguins to develop the largest flippers and have the largest body mass in order to adapt.
```{python}
#| label: Affect of environment on Penguins
#| code-summary: Compares the flipper length and body of penguins from different islands.
#| fig-cap: "Environment and growth"
#| fig-align: center
# Include and execute your code here

# Load the penguins dataset
penguins = load_penguins()

LetsPlot.setup_html()
(ggplot(
  data = penguins,
  mapping = aes(x = "flipper_length_mm", y = "body_mass_g", color = "island")
) +
### Body mass and flipper length are compared variables, Island of origin is plotted to find relationship between environment and size.
  geom_point() +
  geom_smooth(se = False))

```

## Question|Task 2

Include the table created from PY4DS: CH2 Data Visualization used to create the above chart.

Below is the raw data that the chart above was produced from. 
```{python}
#| label: Affect of Islands on Flipper and body mass
#| code-summary: Islands, Flipper, Body Mass
#| tbl-cap: "Affect of Islands on Flipper and body mass"
#| tbl-cap-location: top
# Include and execute your code here
    
import pandas as pd
from palmerpenguins import load_penguins
penguins = load_penguins()
demonstrate = ['island', 'flipper_length_mm', 'body_mass_g']

print(penguins)
```